Dev/ci setup
cpp-park-vk-education/2022_2_MOND pull request #2
Opened 2022-10-22 05:48 UTC by MoraPresence

2022-11-10 01:22 UTC, Arugaf requested changes
Статический анализ кода стоит проводить до билда.

Не хватает пустых строк в конце файлов.

Нет возможности собрать код с санитайзерами, При этом валгринд, естественно, должен запускаться на сборке без санитайзеров.

Юнит тесты отдельно должны запускаться на релизной сборке.

Лично я бы запускал валгринд на каких-нибудь интеграционных тестах, хотя это спорный вопрос.

Не генерируется и не выгружается отчет о покрытии.

Нет заготовки cmake-файла непосредственно для будущего приложения (или приложений) со всеми необходимым флагами, опциями, переменными и настройками.

Нет полноценных clang-format и clang-tidy конфигов.

Кажется, что пустой docker-compose.yml в репозитории лишний.

Пока без оценки.

2022-11-10 01:22 UTC, Arugaf commented on CMakeLists.txt
> +option(BUILD_FOR_TEST "Build for test" OFF)
Не очень хорошее название флага.

2022-11-10 01:22 UTC, Arugaf commented on CMakeLists.txt
> +
Надо причесать форматирование.

2022-11-10 01:22 UTC, Arugaf commented on README.md
> +MOND DB ci_setup_branch
Немножко странно менять ридми в каждой ветке?

2022-11-10 01:22 UTC, Arugaf commented on Tests/CMakeLists.txt
> +    set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -coverage -lgcov" )
Дублируется?

2022-11-10 01:22 UTC, Arugaf commented on Tests/CMakeLists.txt
> +file(GLOB SOURCES *.cpp)
Не используем директиву file.

2022-11-10 01:22 UTC, Arugaf commented on Tests/CMakeLists.txt
> +
Надо бы причесать форматирование.

2022-11-10 01:22 UTC, Arugaf commented on Tests/CMakeLists.txt
> +#FetchContent_MakeAvailable(googletest)
Нерабочие комментарии.

2022-11-10 01:22 UTC, Arugaf commented on artefacts/README.md
> +This directory for artefacts
Опечатка?

2022-11-10 01:22 UTC, Arugaf commented on Tests/tests.cpp
> +}
Хочется увидеть какой-нибудь тестовый тест.

2022-11-10 01:22 UTC, Arugaf commented on linters/CPPLINT.cfg
> +filter=-readability/casting
Непонятно по какому принципу были выбраны фильтры.

2022-11-10 01:22 UTC, Arugaf commented on linters/linters.sh
> +print_header "SUCCESS"
Хочется увидеть полноценный свой скрипт.

2022-11-10 09:43 UTC, MoraPresence commented on .github/workflows/CI.yml
> +      #        run: cmake --build ${{github.workspace}}/build
✓

2022-11-10 09:44 UTC, MoraPresence commented on .github/workflows/CI.yml
> +          valgrind --tool=memcheck --leak-check=yes ${{github.workspace}}/build/Tests/MOND_DB_TESTS
✓

2022-11-10 09:44 UTC, MoraPresence commented on .github/workflows/CI.yml
> +          valgrind --tool=memcheck --leak-check=yes ${{github.workspace}}/build/Tests/MOND_DB_TESTS
✓

2022-11-10 09:46 UTC, MoraPresence commented on CMakeLists.txt
> +
✓

2022-11-10 09:47 UTC, MoraPresence commented on README.md
> +MOND DB ci_setup_branch
✓

2022-11-10 09:48 UTC, MoraPresence commented on Tests/CMakeLists.txt
> +file(GLOB SOURCES *.cpp)
✓

2022-11-10 09:49 UTC, MoraPresence commented on Tests/CMakeLists.txt
> +
✓

2022-11-10 09:49 UTC, MoraPresence commented on Tests/CMakeLists.txt
> +#FetchContent_MakeAvailable(googletest)
✓

2022-11-10 09:49 UTC, MoraPresence commented on artefacts/README.md
> +This directory for artefacts
✓

2022-11-10 10:36 UTC, MoraPresence commented on .github/workflows/CI.yml
> +    branches: [ "main", "workflow_setup", "dev/ci_setup", "dev/MoraPresence", "dev/Nikitylllka", "dev/ogrebatel", "dev/darioshka" ]
✓

2022-11-10 13:46 UTC, MoraPresence commented on .github/workflows/CI.yml
> +          ./linters/linters.sh
✓

2022-11-10 13:46 UTC, MoraPresence commented on .github/workflows/CI.yml
> +          ./MOND_DB_TESTS
✓

2022-11-10 13:46 UTC, MoraPresence commented on CMakeLists.txt
> +option(BUILD_FOR_TEST "Build for test" OFF)
✓

2022-11-22 10:57 UTC, Arugaf requested changes
Александр - 10;
Олег - 10;
Никита - 8;
Дарья - 7;

2022-12-20 11:04 UTC, merged